name = "cloud"
compatibility_date = "2026-06-08"
main = "backend/index.ts"

[[d1_databases]]
binding = "DB"
database_name = "cloudcalf"
database_id = "local"
migrations_dir = "../db/migrations"

[assets]
directory = "./dist/client"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[vars]
GITHUB_CLIENT_ID = ""
GITHUB_CLIENT_SECRET = ""
CLOUDFLARE_ACCOUNT_ID = ""
CLOUDFLARE_API_TOKEN = ""
