packages:
  - plugin
  - example
  - cloud

catalogMode: prefer

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
  "@vitejs/plugin-react": ^6.0.2
  react: ^19.2.7
  react-dom: ^19.2.7
  "@cloudflare/vite-plugin": ^1.41.0
  hono: ^4.12.25
allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
